package Interface;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.ImageIcon;

import Code.All;
import Code.user;
import Server.Client;

import javax.swing.JButton;
import javax.swing.JOptionPane;

import java.awt.event.ActionListener;
import java.io.IOException;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import java.awt.Toolkit;

/**
 *
 * @author  __USER__
 */
public class Chatroom extends javax.swing.JFrame {
	
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JPanel jPanel1;
	private JButton button;
	private JButton button_1;
	private JButton button_2;
	private JButton button_3;
	private JButton button_4;
	private JButton button_5;
	private JButton button_6;
	private JButton button_7;
	private JButton button_8;
	private JButton button_9;

	/** Creates new form Chatroom */
	public Chatroom() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(Chatroom.class.getResource("/img/\u56FE\u6807.png")));
		setResizable(false);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLayeredPane1 = new javax.swing.JLayeredPane();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		jLabel22 = new javax.swing.JLabel();
		jLabel23 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setText("\u8868\u767D");

		jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel18.setText("\u597D\u611F\u5EA6\uFF1A");
		jLabel18.setBounds(848, 736, 104, 32);
		jLayeredPane1.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel19.setBounds(402, 98, 70, 30);
		jLayeredPane1.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel20.setText("\u597D\u611F\u5EA6\uFF1A");
		jLabel20.setBounds(848, 449, 104, 32);
		jLayeredPane1.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel21.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel21.setBounds(410, 389, 70, 30);
		jLayeredPane1.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel22.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel22.setText("\u597D\u611F\u5EA6\uFF1A");
		jLabel22.setBounds(302, 711, 96, 32);
		jLayeredPane1.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel23.setBounds(952, 130, 76, 30);
		jLayeredPane1.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel14.setText("\u597D\u611F\u5EA6\uFF1A");
		jLabel14.setBounds(848, 129, 104, 32);
		jLayeredPane1.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel15.setBounds(412, 712, 70, 30);
		jLayeredPane1.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel16.setText("\u597D\u611F\u5EA6\uFF1A");
		jLabel16.setBounds(302, 388, 104, 32);
		jLayeredPane1.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel17.setBounds(954, 737, 74, 30);
		jLayeredPane1.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel9.setBounds(962, 450, 76, 30);
		jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel8.setText("\u597D\u611F\u5EA6:");
		jLabel8.setBounds(302, 97, 180, 32);
		jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/男2.jpg"))); // NOI18N
		jLabel3.setBounds(98, 388, 180, 200);
		jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/男3.jpg"))); // NOI18N
		jLabel4.setBounds(1038, 129, 180, 200);
		jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/女3.jpg"))); // NOI18N
		jLabel5.setBounds(1038, 736, 180, 200);
		jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/女2.jpg"))); // NOI18N
		jLabel6.setBounds(98, 711, 180, 200);
		jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/女1.jpg"))); // NOI18N
		jLabel7.setBounds(1038, 449, 180, 200);
		jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel2.setIcon(new ImageIcon(Chatroom.class.getResource("/img/\u75371.png"))); // NOI18N
		jLabel2.setBounds(98, 97, 180, 200);
		jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
		
		JButton btnNewButton = new JButton("\u7ED9\u4ED6\u9001\u793C");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					All.gift(user.getChoosename(), 1, jLabel19.getText());
					money();
					Show();
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		btnNewButton.setBounds(302, 138, 113, 27);
		jLayeredPane1.add(btnNewButton);
		
		JButton btnNewButton_1 = new JButton("\u8868\u767D");
		btnNewButton_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					confession(1, jLabel19.getText());
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		btnNewButton_1.setBounds(302, 175, 113, 27);
		jLayeredPane1.add(btnNewButton_1);
		
		button = new JButton("\u8868\u767D");
		button.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					confession(2, jLabel21.getText());
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		button.setBounds(302, 466, 113, 27);
		jLayeredPane1.add(button);
		
		button_1 = new JButton("\u7ED9\u4ED6\u9001\u793C");
		button_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					All.gift(user.getChoosename(), 2, jLabel21.getText());
					money();
					Show();
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		button_1.setBounds(302, 429, 113, 27);
		jLayeredPane1.add(button_1);
		
		button_2 = new JButton("\u8868\u767D");
		button_2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					confession(3, jLabel23.getText());
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		button_2.setBounds(848, 207, 113, 27);
		jLayeredPane1.add(button_2);
		
		button_3 = new JButton("\u7ED9\u4ED6\u9001\u793C");
		button_3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					All.gift(user.getChoosename(), 3, jLabel23.getText());
					money();
					Show();
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		button_3.setBounds(848, 170, 113, 27);
		jLayeredPane1.add(button_3);
		
		button_4 = new JButton("\u8868\u767D");
		button_4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					confession(4, jLabel15.getText());
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		button_4.setBounds(302, 790, 113, 27);
		jLayeredPane1.add(button_4);
		
		button_5 = new JButton("\u7ED9\u5979\u9001\u793C");
		button_5.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					All.gift(user.getChoosename(), 4, jLabel15.getText());
					money();
					Show();
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		button_5.setBounds(302, 753, 113, 27);
		jLayeredPane1.add(button_5);
		
		button_6 = new JButton("\u8868\u767D");
		button_6.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					confession(5, jLabel17.getText());
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		button_6.setBounds(848, 815, 113, 27);
		jLayeredPane1.add(button_6);
		
		button_7 = new JButton("\u7ED9\u5979\u9001\u793C");
		button_7.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					All.gift(user.getChoosename(), 5, jLabel17.getText());
					money();
					Show();
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		button_7.setBounds(848, 778, 113, 27);
		jLayeredPane1.add(button_7);
		
		button_8 = new JButton("\u8868\u767D");
		button_8.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					confession(6, jLabel9.getText());
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		button_8.setBounds(848, 527, 113, 27);
		jLayeredPane1.add(button_8);
		
		button_9 = new JButton("\u7ED9\u5979\u9001\u793C");
		button_9.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					All.gift(user.getChoosename(), 6, jLabel9.getText());
					money();
					Show();
				} catch (ClassNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		button_9.setBounds(848, 490, 113, 27);
		jLayeredPane1.add(button_9);

		jLabel1.setIcon(new ImageIcon(Chatroom.class.getResource("/img/\u68113.jpg"))); // NOI18N
		jLabel1.setBounds(0, 0, 1280, 958);
		jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1281,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 958,
				Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
		try {
			Show();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Chatroom().setVisible(true);
			}
		});
	}
	
	public void Show() throws ClassNotFoundException, SQLException, IOException {
		String[] a = All.love(user.getChoosename());
		jLabel19.setText(a[0] + "");
		jLabel21.setText(a[1] + "");
		jLabel23.setText(a[2] + "");
		jLabel15.setText(a[3] + "");
		jLabel17.setText(a[4] + "");
		jLabel9.setText(a[5] + "");
	}
	
	public void money() throws ClassNotFoundException, SQLException, IOException {
		int money = All.money(user.getChoosename());
		if (money < 100) {
			JOptionPane.showMessageDialog(null,"你已经没钱了，别泡妞了！");
			return;
		}
		money = money - 15;
		All.money(user.getChoosename(),money);
		InterFace.label_22.setText(money + "");
	}
	
	public void confession(int number, String str) throws ClassNotFoundException, SQLException, IOException {
		int a = All.Confession(user.getChoosename(), number, str);
		if(a == 1 || a == 2) {
			try {
				Show();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
}